### ISSUE TITLE
Render Dice not working on v11

### ISSUE THREAD

**Issue by igorteuri** [dddice/dddice-foundry-plugin#5]
Whenever I activate the Render Dice feature, the module just doesn't show the 3D dice in FVTT, and shows the following error:
![image](https://github.com/dddice/dddice-foundry-plugin/assets/64547748/c1adc1bd-a7fe-40df-ac21-fbfe87d2858c)

My foundry and system version is showed down bellow:
![image](https://github.com/dddice/dddice-foundry-plugin/assets/64547748/b87c47f8-e51a-49d0-ae15-d327cc38a022)

I'm properly connected via API
![image](https://github.com/dddice/dddice-foundry-plugin/assets/64547748/457acae8-4122-481d-be40-e3ab921964d3)

**Comment by CelesteBloodreign** [comment]
I just posted a new release candidate today. I would appreciate it if you might manually install it and see if your issue occurs on that new version as well?

The browser's error log would also be useful, if you are comfortable posting a screenshot of that.

**Comment by igorteuri** [comment]
Hi there!
Thanks for answering and sorry for the delayed reply. 

I have manually installe v0.5.0-rc., but unfortunatelly it still doesn`t work. 
Here`s the error I see in foundry UI
![image](https://github.com/dddice/dddice-foundry-plugin/assets/64547748/c64bb51d-bb24-43f3-8b55-ac765e665824)

Here's the error in console
![image](https://github.com/dddice/dddice-foundry-plugin/assets/64547748/2cf979b9-124b-4a35-894c-e22486c3fca9)

![image](https://github.com/dddice/dddice-foundry-plugin/assets/64547748/a4bad4d7-c22b-46f8-9554-a08378e631c3)

**Comment by CelesteBloodreign** [comment]
Thanks for replying! I have tried to reproduce this by creating a new world using the Custom system builder v3.0.0 and Foundry VTT v11.313 and wasn't able to get the same error you did.

I enabled dddice, with render mode on, and then used `/roll 1d20` and `/roll 6d6` and the dice worked as expected with no errors.

I'd like to try and help more, might you be able to write me a series of steps to follow that got you to your error?

Is dddice the only module you have installed in this world? If not could you try disabling all other modules and see if the error continues?

**Comment by igorteuri** [comment]
Sorry for the incovenience. The problem was with my browser. I was using ripper93's VTT browser (https://github.com/theripper93/fvtt-player-client) and dddice doesnt work there, even if all modules are disabled. 

I tried on Chorme, and worked perfectly. 
Again, sorry for the trouble.

**Comment by CelesteBloodreign** [comment]
Thanks for letting me know!

I was unaware that browser was a thing. I will give it a look. It might be
easy to get it to work in that browse!

**Comment by igorteuri** [comment]
There`s also the FLC, another browser suited only for FVTT. 
I opened an issue in the VTT Desktop Client Github as well. Maybe could be something realted to the way the browser works. Layman here, I couln`t tell. 

Thanks for your support!

**Comment by CelesteBloodreign** [comment]
All browsers are different, so it's entirely possible. I was able to run the module in VTT Desktop Client and reproduce the error you saw. 

I have developed a fix and this will be included in the next release

**Comment by igorteuri** [comment]
OMG!
Thank you a lot for your amazing work!

**Comment by CelesteBloodreign** [comment]
v0.5.0 has been released! Give it a try, this should now be compatible with VTT Desktop Client 👍
